theme: jekyll-theme-cayman
title: Evolution of prediction of protein structure
description: Neural networks or deep learning powers AlphaFold and other modernized tools for prediction of protein structures
