theme: jekyll-theme-cayman
title: Graphs & Networks
description: Understanding how components or objects in a system act together, utilizing mathematical structures that model pairwise interactions between them.
